---
- name: Ensure CPU supports KVM acceleration
  command: egrep -c '(vmx|svm)' /proc/cpuinfo
  register: kvm_support
  changed_when: false
  failed_when: kvm_support.stdout == "0"

- name: Install KVM and required packages
  apt:
    name:
      - qemu-kvm
      - libvirt-daemon-system
      - libvirt-clients
      - bridge-utils
      - libosinfo-bin
      - virt-top
      - libguestfs-tools
    state: present
  when: kvm_support.stdout != "0"

- name: Check if ansible user exists
  getent:
    database: passwd
    key: ansible
  register: ansible_user
  changed_when: false

- name: Create ansible group if it does not exist
  group:
    name: ansible
    state: present
  when: ansible_user is not defined

- name: Create ansible user if it does not exist
  user:
    name: ansible
    group: ansible
    state: present
  when: ansible_user is not defined

- name: Add ansible user to libvirt group
  user:
    name: ansible
    groups: libvirt
    append: yes

- name: Add ansible user to kvm group
  user:
    name: ansible
    groups: kvm
    append: yes

- name: Ensure libvirt service is started and enabled
  service:
    name: libvirtd
    state: started
    enabled: yes
    
- name: Create VLAN configuration files
  template:
    src: vlan_template.xml.j2
    dest: "/etc/libvirt/qemu/networks/kvmbr{{ item }}.xml"
  with_items: "{{ vlans }}"

- name: Check network list
  command: "virsh net-list --all"
  register: network_list
  changed_when: false

- name: Define the network if not already defined
  command: "virsh net-define /etc/libvirt/qemu/networks/kvmbr{{ item }}.xml"
  when: "'kvmbr{{ item }}' not in network_list.stdout"
  with_items: "{{ vlans }}"
  register: define_results
  ignore_errors: yes

- name: Check active network list
  command: "virsh net-list --all"
  register: active_network_list
  changed_when: false

- name: Start the network if not already started
  command: "virsh net-start kvmbr{{ item }}"
  when: "'kvmbr{{ item }}' not in active_network_list.stdout"
  with_items: "{{ vlans }}"
  register: start_results
  ignore_errors: yes

- name: Check autostart network list
  command: "virsh net-list --autostart"
  register: autostart_network_list
  changed_when: false

- name: Ensure network is set to autostart
  command: "virsh net-autostart kvmbr{{ item }}"
  when: "'kvmbr{{ item }}' not in autostart_network_list.stdout"
  with_items: "{{ vlans }}"
  register: autostart_results
  ignore_errors: yes
