---
# install_docker.yml
# Installs Docker, initiates a docker swarm, and sets up traefik reverse proxy

- name: Install Docker
  hosts: docker-*
  become: yes
  become_user: root
  roles:
    - docker
