---
all:
  vars:
    ansible_user: root
  children:
    servers:
      hosts:
        docker-00.303bpr.org:
        docker-01.303bpr.org:
        docker-02.303bpr.org:
        kvm-00.303bpr.org:
        prntsrv-00.303bpr.org:
    kvm_servers:
      hosts:
        kvm-00.303bpr.org:
          ansible_connection: local
    print_servers:
      hosts:
        prntsrv-00.303bpr.org:
    docker_swarm:
      hosts:
        docker-00.303bpr.org:
        docker-01.303bpr.org:
        docker-02.303bpr.org:
    docker_managers:
      hosts:
        docker-00.303bpr.org:
    docker_workers:
      hosts:
        docker-01.303bpr.org:
        docker-02.303bpr.org:

